[workspace]
resolver = "2"
members = [
    "record_registry",
    "access_control",
    "provider_registry",
    "shared",
]

[workspace.dependencies]
soroban-sdk = "22.0.8"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
